services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Maispace\MaiSeo\:
        resource: '../Classes/*'
        exclude:
            - '../Classes/Domain/Model/*'
            - '../Classes/Event/*'

    Maispace\MaiSeo\Schema\VocabularyRegistry:
        public: true

    Maispace\MaiSeo\StructuredData\StructuredDataService:
        public: true

    Maispace\MaiSeo\StructuredData\AutoGenerator:
        public: true

    Maispace\MaiSeo\StructuredData\Collector\CollectorRegistry:
        public: true

    Maispace\MaiSeo\DataProcessing\StructuredDataProcessor:
        public: true

    Maispace\MaiSeo\MetaTag\OpenGraphMetaTagGenerator:
        public: true

    Maispace\MaiSeo\MetaTag\OpenGraphValueResolver:
        public: true

    Maispace\MaiSeo\Hook\PageRecordSaveHook:
        public: true

    Maispace\MaiSeo\Hook\ExtensionRecordSaveHook:
        public: true

    Maispace\MaiSeo\StructuredData\Collector\PageCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\BreadcrumbCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\NewsArticleCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\JobPostingCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\PersonCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\PlaceCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\OrganizationCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\FaqCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\StructuredData\Collector\EventCollector:
        tags:
            - name: 'maiseo.structured_data.collector'

    Maispace\MaiSeo\EventListener\PageRecordSavedListener:
        tags:
            - name: 'event.listener'
              identifier: 'maiseo/page-record-saved'
              event: Maispace\MaiSeo\Event\PageRecordSavedEvent

    Maispace\MaiSeo\Form\Element\StructuredDataTreeElement:
        tags:
            - name: 'backend.form.element'
              identifier: 'maiseoStructuredDataTree'
