categories:
  mai-seo: ~
  mai-seo.sitemap:
    parent: mai-seo
  mai-seo.languageRedirect:
    parent: mai-seo

settings:
  seo.sitemap.records.storagePid:
    default: 27
    type: page
    category: mai-seo.sitemap
  seo.sitemap.records.news.detailPid:
    default: 12
    type: page
    category: mai-seo.sitemap
  seo.sitemap.records.jobs.detailPid:
    default: 14
    type: page
    category: mai-seo.sitemap
  seo.sitemap.records.locations.detailPid:
    default: 0
    type: page
    category: mai-seo.sitemap
  seo.sitemap.records.team.detailPid:
    default: 0
    type: page
    category: mai-seo.sitemap
  seo.sitemap.records.gallery.detailPid:
    default: 0
    type: page
    category: mai-seo.sitemap
  seo.languageRedirect.enabled:
    default: true
    type: bool
    category: mai-seo.languageRedirect
  seo.languageRedirect.rootOnly:
    default: true
    type: bool
    category: mai-seo.languageRedirect
  seo.languageRedirect.cookieName:
    default: 'mai_seo_lang'
    type: string
    category: mai-seo.languageRedirect
  seo.languageRedirect.cookieLifetime:
    default: 31536000
    type: int
    category: mai-seo.languageRedirect
